services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mchat
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
