version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mchat
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
