version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mchat
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: unless-stopped
    command: dragonfly --proactor_threads=4
    ports:
      - 6379:6379
    ulimits:
      memlock: -1
