version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseerkt
      MONGO_INITDB_ROOT_PASSWORD: secret
  redis:
    image: redis:7.2-alpine
    restart: always
