services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mchat
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: unless-stopped
    command: dragonfly --proactor_threads=4
    ports:
      - 6379:6379
    ulimits:
      memlock: -1
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: mchat-app
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
      dragonfly:
        condition: service_healthy
