name: mChat Web CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/client-ci.yml
      - web/*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/client-ci.yml
      - web/*


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --filter web

      - name: Lint
        run: pnpm --filter web lint

      - name: Build
        run: pnpm --filter web build
      
        
    