name: mChat Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
        
      - name: Replace pnpm workspace file
        run: cp pnpm-workspace.prod.yaml pnpm-workspace.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        env:
          VITE_BACKEND_URL: https://${{ secrets.APP_DOMAIN }}
        run: pnpm build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: mchat_build
          path: |
            server
            web/dist
            infra/ec2


  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: mchat_build

      - name: Move static files
        run: |
          sudo rm -rf /var/www/html/*
          sudo mv web/dist/* /var/www/html/
          sudo rm -rf web/dist

      - name: Reload caddy service
        run: |
          sudo systemctl reload caddy

      # - name: Set server env file
      #   run:
      #     cd server && cp .env.example .env
        
      - name: Restart application
        run: pm2 restart mchat

        
    